name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-ttf-dev
    - name: make
      run: make
    - name: make clean
      run: make clean